# Nivel de logging general para tu aplicación
logging.level.com.lazysyntax.nutron.nutrition=INFO
logging.level.root=INFO
#O DEBUG si quieres ver más logs de Spring en general

spring.application.name=nutron-nutrition
server.port=8082

# Configuración para la Base de Datos en Docker
spring.datasource.url=jdbc:mysql://${DB_HOST:nutrition-db}:3306/${DB_NAME:nutrition_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:nutrition_password}

# Esto ayuda a Hibernate a no tener que "adivinar" el dialecto si la red está lenta
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Crear tablas automáticamente basado en tus clases Java
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Clave de cifrado JWT genearado con openssl rand -base64 48 en Powershell(Terminal)
# jwt.secret=fvSxRZ1jZEXo1Z5ehhl4FOqS0dAuFIsaKMkVZ4ZJsY55Zl71W63o/cOIpCsCOr/L
# Sintaxis para leer la variable de Docker, con un valor por defecto para desarrollo local
jwt.secret=${JWT_SECRET:fvSxRZ1jZEXo1Z5ehhl4FOqS0dAuFIsaKMkVZ4ZJsY55Zl71W63o/cOIpCsCOr/L}
# Habilita el filtro de logging de peticiones
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Esto es para logs de Tomcat, no del filtro de Spring
# Opcional: Configura el prefijo y sufijo del log para el filtro
server.tomcat.accesslog.enabled=true

