services:
  # --- CAPA DE DATOS ---
  
  # Base de datos relacional para Usuarios
  mysql-db:
    image: mysql:8.0
    container_name: nutron-mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=auth_db
      - MYSQL_ROOT_PASSWORD=root_password
      - TZ=Europe/Madrid # Sincroniza la zona horaria en MySQL
    volumes:
      - /etc/localtime:/etc/localtime:ro # Lee la hora del host
    ports:
      - "3306:3306"
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Base de datos NoSQL para el Diario
  # ...

  # --- CAPA DE APLICACIÓN (JAVA) ---

  # Microservicio de Autenticación (MySQL)
  auth-service:
    build: ./nutron-auth # Ruta a la carpeta de tu primer proyecto Java
    container_name: nutron-auth-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=auth_db
      - DB_USER=root
      - DB_PASS=root_password
      - TZ=Europe/Madrid # Define la zona horaria para el contenedor Linux
    volumes:
      - /etc/localtime:/etc/localtime:ro # Refuerza la hora local para la JVM
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - backend-net

  # Microservicio de Diario (MongoDB)
  # ... 

networks:
  backend-net:
    driver: bridge