services:
  database:
    image: mongo:latest
    container_name: nutron-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./nutron-docker/mongodb/data:/data/db # Persistencia local
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=nutron_pass

  backend:
    image: tomcat:9.0-jdk17-openjdk
    container_name: nutron-api
    ports:
      - "8080:8080"
    volumes:
      # Mapeamos el WAR generado por el proyecto Java al Tomcat
      - ./nutron-api-rest/build/libs/nutron-api.war:/usr/local/tomcat/webapps/nutron-api.war
    depends_on:
      - database
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:nutron_pass@database:27017/nutron_db?authSource=admin