package com.lazysyntax.nutron.nutrition.service;

import com.lazysyntax.nutron.nutrition.model.dto.MealRequest.FoodDto;
import com.lazysyntax.nutron.nutrition.model.entity.Food;
import com.lazysyntax.nutron.nutrition.repository.FoodRepository;
import com.lazysyntax.nutron.nutrition.util.FoodConverters;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Service
public class FoodService {

    private final FoodRepository foodRepository;

    @Autowired
    public FoodService(FoodRepository foodRepository) {
        this.foodRepository = foodRepository;
    }

    @Transactional
    public Food createFood(FoodDto foodDto) {
        // Convert FoodDto to Food entity (foodId will be generated by DB)
        Food food = FoodConverters.toEntity(foodDto);
        // Save the new food item
        return foodRepository.save(food);
    }

    @Transactional
    public Food updateFood(String foodId, FoodDto foodDto) {
        // Logic to find and update an existing food item
        Optional<Food> existingFoodOptional = foodRepository.findById(foodId);

        if (existingFoodOptional.isPresent()) {
            Food existingFood = existingFoodOptional.get();
            // Update the existing entity with data from the DTO
            FoodConverters.updateEntity(foodDto, existingFood);
            return foodRepository.save(existingFood);
        } else {
            // Food not found, you might want to throw an exception or return null
            return null;
        }
    }

    @Transactional
    public void deleteFood(String foodId) {
        // Logic to delete a food item by ID
        foodRepository.deleteById(foodId);
    }

    @Transactional(readOnly = true)
    public Food getFoodById(String foodId) {
        // Logic to get a food item by ID
        return foodRepository.findById(foodId).orElse(null);
    }

    @Transactional(readOnly = true)
    public List<Food> getAllFoods() {
        // Logic to get all food items
        return foodRepository.findAll();
    }
}
